# Generated by Django 5.0.1 on 2026-01-17 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_alter_curriculum_id_alter_subject_id"),
        ("students", "0003_alter_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculum",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="curriculum",
            index=models.Index(fields=["grade"], name="curriculum__grade_i_b6f7f5_idx"),
        ),
        migrations.AddIndex(
            model_name="curriculum",
            index=models.Index(
                fields=["subject"], name="curriculum__subject_29c3c7_idx"
            ),
        ),
    ]
