# Generated by Django 5.0.1 on 2026-01-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                            ("HOLIDAY", "Holiday"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("marked_by", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="attendance__student_76a8d7_idx",
                    ),
                    models.Index(fields=["date"], name="attendance__date_61f2e1_idx"),
                    models.Index(fields=["type"], name="attendance__type_4a846a_idx"),
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("present_days", models.IntegerField(default=0)),
                ("absent_days", models.IntegerField(default=0)),
                ("late_days", models.IntegerField(default=0)),
                ("excused_days", models.IntegerField(default=0)),
                ("total_working_days", models.IntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "month", "year"],
                        name="attendance__student_04479d_idx",
                    )
                ],
                "unique_together": {("student", "month", "year")},
            },
        ),
    ]
