# Generated by Django 5.0.1 on 2026-01-17 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_id_alter_attendancesummary_id"),
        ("students", "0003_alter_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesummary",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["year", "month"], name="attendance__year_05e6f4_idx"
            ),
        ),
    ]
