# Generated by Django 5.0.1 on 2026-01-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("capacity", models.IntegerField()),
                ("warden_name", models.CharField(max_length=100)),
                ("warden_phone", models.CharField(max_length=20)),
                ("facilities", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="hostel_host_code_ffa47f_idx"),
                    models.Index(
                        fields=["status"], name="hostel_host_status_5c91e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("room_number", models.CharField(max_length=20)),
                ("floor", models.IntegerField()),
                ("capacity", models.IntegerField(default=4)),
                ("current_occupancy", models.IntegerField(default=0)),
                ("facilities", models.TextField(blank=True, null=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hostel.hostel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("allocated_from", models.DateField()),
                ("allocated_until", models.DateField(blank=True, null=True)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("academic_year", models.CharField(max_length=50)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hostel.room"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["hostel"], name="hostel_room_hostel__31ffc7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hostel", "room_number")},
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(
                fields=["student"], name="hostel_host_student_9f4ca8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(fields=["room"], name="hostel_host_room_id_88c228_idx"),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(fields=["status"], name="hostel_host_status_b189cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="hostelallocation",
            unique_together={("student", "academic_year")},
        ),
    ]
