# Generated by Django 5.0.1 on 2026-01-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("join_date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TEACHING", "Teaching"),
                            ("NON_TEACHING", "Non-Teaching"),
                            ("ADMIN", "Administrative"),
                            ("SUPPORT", "Support"),
                        ],
                        default="TEACHING",
                        max_length=20,
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("qualification", models.TextField()),
                ("experience", models.IntegerField(default=0)),
                ("subjects", models.JSONField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff/photos/"),
                ),
                ("documents", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_grades",
                    models.ManyToManyField(blank=True, to="students.grade"),
                ),
                (
                    "assigned_sections",
                    models.ManyToManyField(blank=True, to="students.section"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["type"], name="staff_staff_type_22e4e9_idx"),
                    models.Index(
                        fields=["department"], name="staff_staff_departm_eea1cc_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="staff_staff_is_acti_0db61a_idx"
                    ),
                    models.Index(fields=["email"], name="staff_staff_email_87de38_idx"),
                ],
            },
        ),
    ]
