# Generated by Django 5.0.1 on 2026-01-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("subject", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "Announcement"),
                            ("NOTIFICATION", "Notification"),
                            ("PRIVATE", "Private Message"),
                        ],
                        default="PRIVATE",
                        max_length=20,
                    ),
                ),
                ("priority", models.CharField(default="NORMAL", max_length=20)),
                ("is_broadcast", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages",
                through="messaging.MessageRecipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["recipient"], name="messaging_m_recipie_efdf32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["is_read"], name="messaging_m_is_read_1a278e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "recipient")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender"], name="messaging_m_sender__259b0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="messaging_m_message_9677d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="messaging_m_created_d51bc4_idx"
            ),
        ),
    ]
