# Generated by Django 5.0.1 on 2026-01-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "behavior_type",
                    models.CharField(
                        choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("severity", models.CharField(default="MEDIUM", max_length=20)),
                ("points", models.IntegerField(default=0)),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_behaviors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student"], name="behavior_be_student_bca62e_idx"
                    ),
                    models.Index(
                        fields=["behavior_type"], name="behavior_be_behavio_0ed06e_idx"
                    ),
                    models.Index(fields=["date"], name="behavior_be_date_6014a9_idx"),
                    models.Index(
                        fields=["is_resolved"], name="behavior_be_is_reso_316424_idx"
                    ),
                ],
            },
        ),
    ]
