# Generated by Django 5.0.1 on 2026-01-17 20:11

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0002_alter_academicyear_id_alter_grade_id_alter_parent_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_date"], name="students_st_admissi_4d51f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["date_of_birth"], name="students_st_date_of_a50842_idx"
            ),
        ),
    ]
