# Generated by Django 5.0.1 on 2026-01-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("vehicle_number", models.CharField(max_length=20, unique=True)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_phone", models.CharField(max_length=20)),
                (
                    "driver_license",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("route", models.CharField(blank=True, max_length=200, null=True)),
                ("fuel_type", models.CharField(blank=True, max_length=20, null=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vehicle_number"], name="transport_v_vehicle_43ae63_idx"
                    ),
                    models.Index(
                        fields=["status"], name="transport_v_status_cc3205_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransportAllocation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("pickup_point", models.CharField(max_length=200)),
                ("pickup_time", models.TimeField()),
                ("drop_point", models.CharField(max_length=200)),
                ("drop_time", models.TimeField()),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("academic_year", models.CharField(max_length=50)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student"], name="transport_t_student_6c7542_idx"
                    ),
                    models.Index(
                        fields=["vehicle"], name="transport_t_vehicle_d5e267_idx"
                    ),
                ],
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
